on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.25.x', '1.26.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6.0.3
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run tests
      run: make race-test
